import { Roboto_Mono } from '@next/font/google'
import "./globals.css";
import LineProvider from "./providers/LineProvider";
import Providers from "./redux/Provider";
import LayoutWrapper from "./layoutWrapper";

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700'], // เลือกน้ำหนักที่ต้องการ
  variable: '--font-roboto-mono' // ใช้ตัวแปร CSS สำหรับฟอนต์นี้
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={robotoMono.variable}
        >
          <LineProvider>
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
          </LineProvider>
        </body>
      </html>
    </Providers>
  );
}
