import "./globals.css";
import { Noto_Sans_Thai } from '@next/font/google'
import LineProvider from "./providers/LineProvider";
import Providers from "./redux/Provider";
import LayoutWrapper from "./layoutWrapper";

const notoSansThai  = Noto_Sans_Thai({
  subsets: ['thai'],
  weight: ['100','200','300','400','500','600','700'], // เลือกน้ำหนักที่ต้องการ
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={notoSansThai.className}
        >
          <LineProvider>
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
          </LineProvider>
        </body>
      </html>
    </Providers>
  );
}
